### ISSUE TITLE
what proxy configuration are consumed by maven?

### ISSUE THREAD

**Issue by ccshih** [redhat-developer/devspaces#123]
I followed the [steps](https://access.redhat.com/documentation/en-us/red_hat_codeready_workspaces_for_openshift/1.0.0/html/administration_guide/installing_codeready-workspaces) to setup codeready.

I find proxy configuration exists in these parameters of `che configmap` but maven still cannot grab pom file.
- CHE_WORKSPACE_MAVEN__OPTIONS
- CHE_WORKSPACE_JAVA_OPTIONS
- CHE_WORKSPACE_HTTP__PROXY__JAVA__OPTIONS
- JAVA_OPTS

proxy configuration:
```
-Dhttp.proxyHost=**** -Dhttp.proxyPort=**** -Dhttps.proxyHost=****  -Dhttps.proxyPort=****
```

Proxy works if I run `curl -x **** https://repo.apache.maven.org/...` in terminal.

Am I missing any configuration? Or any other configuration (ex: env variable) that maven can consume?

BTW, [This document](https://access.redhat.com/documentation/en-us/red_hat_codeready_workspaces_for_openshift/1.0.0/html/administration_guide/installing_codeready-workspaces#proc_configuring-workspace-to-work-behind-https-proxy-server) says I need to **DELETE** some HTTPS-proxy related parameters from the JAVA_OPTS values. It is weird.

**Comment by nickboldt** [comment]
@tsmaeder @svor Any advice here?

**Comment by tsmaeder** [comment]
Since Che 7.x does not know anything about Maven, etc., I would not expect there to be any CHE_Maven... settings. You'll have to set those in the devfile.

**Comment by themr0c** [comment]
As the documentation is almost entirely new for CRW 2.0, I am afraid there is no dedicated section anymore. However the proxy settings are now documented in the "CodeReady Workspaces configMaps fields reference" section of the Installation Guide: https://access.redhat.com/documentation/en-us/red_hat_codeready_workspaces/2.0/html-single/installation_guide/index#codeready-workspaces-configmaps-fields-reference_advanced-configuration-options

**Comment by nickboldt** [comment]
Closing as out of date. See latest docs about settings.xml config for maven here:

https://www.eclipse.org/che/docs/stable/end-user-guide/enabling-maven-artifact-repositories/
