### ISSUE TITLE
python unit testing does not work in code ready workspaces

### ISSUE THREAD

**Issue by guyhoskinsibm** [redhat-developer/devspaces#204]
trying to use unittest package no tests are detected despite there being valid tests in the project.

using pytest framework, tests appear to run and pass but:
 - a warning is raised (this can be surpressed as suggested using the ini file)
 - after testing has completed an error is returned, this means that the correct test pass status is not shown in the IDE (just a ?)
`
============================= test session starts ==============================
platform linux -- Python 3.7.3, pytest-5.3.1, py-1.8.0, pluggy-0.13.0
rootdir: /projects/blah, inifile: pytest.ini
collected 2 items
blah/test/blah_test.py ..                   [100%]
=============================== warnings summary ===============================
/home/theia/.local/lib/python3.7/site-packages/_pytest/junitxml.py:436
  /home/theia/.local/lib/python3.7/site-packages/_pytest/junitxml.py:436: PytestDeprecationWarning: The 'junit_family' default value will change to 'xunit2' in pytest 6.0.
  Add 'junit_family=legacy' to your pytest.ini file to silence this warning and make your suite compatible.
    _issue_warning_captured(deprecated.JUNIT_XML_DEFAULT_FAMILY, config.hook, 2)
-- Docs: https://docs.pytest.org/en/latest/warnings.html
--------------- generated xml file: /tmp/tmp-11z68K1EUvrEqy.xml ----------------
========================= 2 passed, 1 warning in 0.03s =========================
Error: TypeError: Cannot read property '$' of undefined
`

**Comment by nickboldt** [comment]
Which version of CodeReady Workspaces are you using? 

Can you share your devfile and sample project so we can attempt to reproduce the issue?

cc: @tsmaeder

**Comment by nickboldt** [comment]
Fixed in 3.4, see https://issues.redhat.com/browse/CRW-2619
