### ISSUE TITLE
Update Maven version in Quarkus devfile

### ISSUE THREAD

**Issue by ebramirez** [redhat-developer/devspaces#282]
Hi,

In this line it is stated that the maven version is 3.6.0, while the minimum required to run the latest version of Quarkus is 3.6.2

https://github.com/redhat-developer/codeready-workspaces/blob/961b54c226f5a02cf8191c2d6bf4328f3133eca2/dependencies/che-devfile-registry/devfiles/03_java11-quarkus/meta.yaml#L3

**Comment by nickboldt** [comment]
mvm 3.6.3 is in Dev Spaces 3.3's UDI container.
