### ISSUE TITLE
Problem with links in 'Building and publishing VSIX extensions for plugin registry'

### ISSUE THREAD

**Issue by luntan-maker** [redhat-developer/devspaces#312]
Hello,

I am working through the [following](https://github.com/redhat-developer/codeready-workspaces/blob/master/devdoc/building/build-vsix-extension.adoc) and tried clicking the link and my browser cannot find the website. The following links don't work for me:
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CRW_CI/view/Builds/job/vscode-extensions-packaging/
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CRW_CI/view/Builds/job/vscode-extensions-packaging/
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CRW_CI/view/Builds/job/vscode-extensions-packaging/JOB_NUMBER/artifact/

Any advice on building the example?

**Comment by nickboldt** [comment]
those are links to an internal server behind the RH firewall, which has since been replaced by a new one, also not exposed to the public. 

But you can see .jenkinsfiles here: 

https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/crw-jenkins/jobs
