### ISSUE TITLE
Want to add tekton pipelines plugins in our Vscode workspace (devspaces)

### ISSUE THREAD

**Issue by mukulk2020** [redhat-developer/devspaces#819]
REDHAT OCP : 4.10.22
![image](https://user-images.githubusercontent.com/61539926/195498645-8d023e7f-3877-4ad5-98e2-57a761d54ffd.png)

I have installed devspaces through operator hub. After that create a cheCluster instance on this devspace.
Not able to add new tekton plugin. 
I take a reference from below articles as well but not able to add plugin
1) https://eclipse-che.github.io/che-plugin-registry/main/index.json
2) https://access.redhat.com/documentation/en-us/red_hat_codeready_workspaces/2.0/html/administration_guide/customizing-the-devfile-and-plug-in-registries#deploying-registries-in-kubernetes_deploying-the-registries

Please add the proper documentation link so that I can easily follow.

**Comment by nickboldt** [comment]
See https://issues.redhat.com/browse/CRW-3472
